const hindiNamesMap: Record<string, string> = {
  'tomato': 'टमाटर',
  'onion': 'प्याज',
  'potato': 'आलू',
  'cabbage': 'पत्ता गोभी',
  'cauliflower': 'फूल गोभी',
  'carrot': 'गाजर',
  'brinjal': 'बैंगन',
  'chilli': 'मिर्च',
  'green chilli': 'हरी मिर्च',
  'pepper': 'मिर्च',
  'capsicum': 'शिमला मिर्च',
  'chilly capsicum': 'शिमला मिर्च',
  'cucumber': 'खीरा',
  'cucumbar (kheera)': 'खीरा',
  'pumpkin': 'कद्दू',
  'sweet pumpkin': 'मीठा कद्दू',
  'gourd': 'लौकी',
  'bottle gourd': 'लौकी',
  'bitter gourd': 'करेला',
  'ridge gourd': 'तुरई',
  'ridgeguard(tori)': 'तुरई',
  'sponge gourd': 'तोरी',
  'pointed gourd (parval)': 'परवल',
  'round gourd': 'टिंडा',
  'little gourd (kundru)': 'कुंदरू',
  'radish': 'मूली',
  'raddish': 'मूली',
  'beetroot': 'चुकंदर',
  'spinach': 'पालक',
  'coriander': 'धनिया',
  'coriander leaves': 'हरा धनिया',
  'coriander leaves (tazia)': 'हरा धनिया',
  'mint': 'पुदीना',
  'mint(pudina)': 'पुदीना',
  'methi': 'मेथी',
  'methi leaves': 'मेथी पत्ती',
  'ginger': 'अदरक',
  'ginger(green)': 'हरी अदरक',
  'ginger(dry)': 'सूखी अदरक',
  'garlic': 'लहसुन',
  'ladyfinger': 'भिंडी',
  'bhindi(ladies finger)': 'भिंडी',
  'okra': 'भिंडी',
  'beans': 'बीन्स',
  'french beans (frasbean)': 'फ्रेंच बीन्स',
  'peas': 'मटर',
  'peas wet': 'हरी मटर',
  'green peas': 'हरी मटर',
  'drumstick': 'सहजन',
  'guar': 'ग्वार',
  'elephant yam (suran)': 'सूरन',
  'sweet potato': 'शकरकंद',
  'turnip': 'शलजम',
  'leafy vegetable': 'पत्तेदार सब्जी',
  'ashgourd': 'पेठा',
  'apple': 'सेब',
  'mango': 'आम',
  'mango (raw-ripe)': 'कच्चा-पका आम',
  'banana': 'केला',
  'orange': 'संतरा',
  'grapes': 'अंगूर',
  'pomegranate': 'अनार',
  'papaya': 'पपीता',
  'papaya (raw)': 'कच्चा पपीता',
  'watermelon': 'तरबूज',
  'water melon': 'तरबूज',
  'muskmelon': 'खरबूजा',
  'guava': 'अमरूद',
  'pineapple': 'अनानास',
  'lemon': 'नींबू',
  'lime': 'नींबू',
  'mousambi(sweet lime)': 'मौसंबी',
  'kinnow': 'किन्नू',
  'coconut': 'नारियल',
  'amla(nelli kai)': 'आंवला',
  'chikoos(sapota)': 'चीकू',
  'seetapal': 'सीताफल',
  'pear(marasebu)': 'नाशपाती',
  'wheat': 'गेहूं',
  'rice': 'चावल',
  'maize': 'मक्का',
  'bajra': 'बाजरा',
  'jowar': 'ज्वार',
  'ragi': 'रागी',
  'barley': 'जौ',
  'paddy': 'धान',
  'paddy(dhan)(basmati)': 'बासमती धान',
  'paddy(dhan)(common)': 'सामान्य धान',
  'tur': 'तुअर दाल',
  'moong': 'मूंग दाल',
  'urad': 'उड़द दाल',
  'chana': 'चना',
  'masoor': 'मसूर दाल',
  'dal': 'दाल',
  'gram': 'चना',
  'lentil': 'दाल',
  'arhar': 'अरहर दाल',
};

export function getHindiName(commodityName: string): string {
  const normalized = commodityName.toLowerCase().trim();
  
  if (hindiNamesMap[normalized]) {
    return hindiNamesMap[normalized];
  }
  
  for (const [key, value] of Object.entries(hindiNamesMap)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return value;
    }
  }
  
  return commodityName;
}
